routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PrincipalController@index')->name('principal');
Route::get('/perfil/{user}', 'UserProfileController@index')->name('perfilUsuario');

Auth::routes();

Route::group(['middleware'=>['auth']], function(){
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('home/redesSociales', 'SocialController');
Route::get('home/redesSociales', 'SocialController@index')->name('redesSociales');
Route::resource('home/publicaciones', 'PublicationController');
Route::get('home/publicaciones', 'PublicationController@index')->name('publicaciones');
Route::resource('home/perfil', 'ProfileController');
Route::get('home/perfil', 'ProfileController@index')->name('perfil');
});

resources/views/crudSocialNetworks/create.blade.php
@extends('layouts.templateHome')

@section('content')
{{-- @include('common.errors') --}}
<div class="row justify-content-center">
        <div class="col-12 col-lg-12 pb-5">
            <form id="form" class="form-group" method="POST" action="/home/redesSociales" enctype="multipart/form-data">
                    @csrf
                      <div class="card shadow-lg p-0">
                          <div class="card-header bg-primary p-0">
                              <div class="text-white text-center py-2">
                                  <h3 class="font-weight-bold"> Registro de redes sociales</h3>
                              </div>
                          </div>
                          <div class="card-body p-0">
                            <div class="form-group col-12 col-lg-11 mx-auto">
                                <div class="input-group mb-2 my-3 mx-auto">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text bg-gradient-primary"> <i class="fa fa-tag text-white"></i> </div>
                                    </div>
                                    <select aria-label="Icono" id="validationIcon" class="custom-select" name="icon_id" required>
                                      <option disabled selected value="">-- Escoga una red social --</option>
                                      @if (isset($icons) && $icons ?? '')
                                        @foreach ($icons as $i)
                                    <option  value="{{$i->id}}" {{old('icon_id') == $i->id ? 'selected': ''}}>{{$i->name}}</option>
                                        @endforeach
                                        </select>
                                      @endif
                                </div>
                                @error('icon_id')
                                    <small class="text-danger d-block font-weight-bold my-0">{{$message}} <i class="fa fa-exclamation-triangle"></i> </small>
                                @enderror
                                <div class="input-group mb-2 my-2 mx-auto">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text bg-gradient-primary"><i name="icon" class="fa fa-link text-white"></i></div>
                                    </div>
                                <input aria-label="Enlace" type="url" id="validationLink" name="link" class="form-control" value="{{old('link')}}" placeholder="Ingrese el link o enlace (Incluya https)">
                            </div>
                            <small class="text-primary">El campo <b>'Enlace'</b> puede quedar vacío.</small>
                                <div class="input-group mb-2 my-3 mx-auto">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text bg-gradient-primary"><i name="icon" class="fa fa-user text-white"></i></div>
                                    </div>
                                <input aria-label="Nombre de perfil" type="text" id="validationNameProfile" name="nameProfile" class="form-control" value="{{old('nameProfile')}}" placeholder="Ingrese el nombre del perfil o número teléfonico" required>
                            </div>
                            @error('nameProfile')
                                <small class="text-danger d-block font-weight-bold my-0">{{$message}} <i class="fa fa-exclamation-triangle"></i> </small>
                            @enderror
                                <div class="mx-auto my-4">
                                    <a href="{{route('redesSociales')}}" class="btn btn-light mx-auto my-1"> <i class="fa fa-arrow-left mr-2"></i>Volver</a>
                                    <button id="btnSubmit" class="btn btn-primary ml-2 mx-auto">Guardar <i class="fa fa-cloud-upload-alt ml-2"></i></button>
                                </div>
                            </div>    
                          </div>
                      </div>
                  </form>
              </div>
@endsection

resources/views/crudSocialNetworks/edit.blade.php
@extends('layouts.templateHome')

@section('content')
<div class="row justify-content-center">
        <div class="col-12 col-lg-12 pb-5">
          @if (isset($socialNetwork) && $socialNetwork ?? '') 
            <form id="form" class="form-group" method="POST" action="/home/redesSociales/{{$socialNetwork->slug}}" enctype="multipart/form-data">
                @method('PUT')
                        @csrf
                          <div class="card shadow-lg">
                              <div class="card-header bg-primary p-0">
                                  <div class="text-white text-center py-2">
                                      <h3 class="font-weight-bold"> Actualización de redes sociales</h3>
                                  </div>
                              </div>
                              <div class="card-body p-0">
                                <div class="form-group col-12 col-lg-11 mx-auto">
                                    <label for="icon_id" class="text-dark d-block my-2">Red Social</label>
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text bg-gradient-primary"> <i class="fa fa-tag text-white"></i> </div>
                                        </div>
                                        <select aria-label="Icono" id="validationIcon" class="custom-select" name="icon_id" required>
                                          <option disabled selected>-- Escoga una red social--</option>
                                          @if (isset($icons) && $icons ?? '')
                                            @foreach ($icons as $i)
                                            <option  value="{{$i->id}}" @if(isset($socialNetwork->icon_id) && $i->id == $socialNetwork->icon_id) selected @endif>
                                                {{$i->name}}</option>
                                            @endforeach
                                            @endif
                                        </select>
                                    </div>
                                    @error('icon_id')
                                        <small class="text-danger d-block font-weight-bold my-0">{{$message}} <i class="fa fa-exclamation-triangle"></i> </small>
                                    @enderror
                                    <label for="link" class="text-dark d-block my-2">Enlace</label>
                                    <div class="input-group mb-2">
                                          <div class="input-group-prepend">
                                              <div class="input-group-text bg-gradient-primary"><i name="icon" class="fa fa-link text-white"></i></div>
                                          </div>
                                        <input aria-label="Enlace" id="validationLink" type="text" name="link" class="form-control" value="{{$socialNetwork->link}}" placeholder="Ingrese el link">
                                    </div>
                                    <p class="text-primary">El campo <b>'Enlace'</b> puede quedar vacío.</p>
                                    <label for="name_profile" class="text-dark d-block my-2">Nombre del perfil o número</label>
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text bg-gradient-primary"><i name="icon" class="fa fa-user text-white"></i></div>
                                        </div>
                                    <input aria-label="Nombre de perfil" id="validationNameProfile" type="text" name="nameProfile" class="form-control" value="{{$socialNetwork->nameProfile}}" placeholder="Ingrese el nombre del perfil o número teléfonico" required>
                                    </div>
                                    @error('nameProfile')
                                        <small class="text-danger d-block font-weight-bold my-0">{{$message}} <i class="fa fa-exclamation-triangle"></i> </small>
                                    @enderror
                                    <div class="mx-auto my-4">
                                        <a href="{{route('redesSociales')}}" class="btn btn-light mx-auto my-1"> <i class="fa fa-arrow-left mr-2"></i>Volver</a>
                                        <button id="btnSubmit" class="btn btn-primary ml-2 mx-auto">Actualizar <i class="fa fa-cloud-upload-alt ml-2"></i></button>
                                 </div>
                                </div>       
                              </div>
                          </div>
                      </form>
                @endif
              </div>
        </div>
@endsection

resources/views/crudSocialNetworks/index.blade.php
@extends('layouts.templateHome')

@section('content')
          <div class="card shadow-lg mb-4">
            <div class="card-header bg-primary py-3">
              <h4 class="m-0 font-weight-bold text-white">Panel de administración de redes sociales</h4>
            </div>
            <div class="card-body">
              <div class="container-fluid">
            <form class="col-sm-8 col-md-8 col-lg-6 d-none d-sm-inline-block p-0">
              <div class="input-group">
                <input type="text" name="searchSocialNetwork" class="form-control small border text-dark" placeholder="¿Qué buscas?" aria-label="Buscador">
                <div class="input-group-append">
                  <button aria-label="Buscador" class="btn btn-primary" type="submit">
                    <i class="fas fa-search fa-sm"></i>
                  </button>
                </div>
              </div>
            </form>
            <ul class="navbar-nav ml-auto">
              <!-- Boton para abrir la barra de busqueda -->
              <li class="nav-item dropdown no-arrow d-sm-none text-right">
                <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-search fa-fw fa-2x text-primary"></i>
                </a>
                <!-- Fin Boton para abrir la barra de busqueda -->
                <!-- Barra de busqueda en pantallas pequeñas -->
                <div class="dropdown-menu dropdown-menu p-3 shadow" aria-labelledby="searchDropdown">
                  <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                      <input type="text" name="searchSocialNetwork" class="form-control border small text-dark" placeholder="¿Qué buscas?" aria-label="Buscador">
                      <div class="input-group-append">
                        <button aria-label="Buscador" type="submit" class="btn btn-primary">
                          <i class="fas fa-search fa-sm"></i>
                        </button>
                      </div>
                    </div>
                  </form>
                </div>
                  <!-- Fin Barra de busqueda en pantallas pequeñas -->
              </li>
            </ul>
              <!-- Resultados de búsqueda-->
              <div class="my-2">
                @if(isset($query) && $query ?? '') 
                  <div class="alert alert-success">
                    <h6 class="d-inline">
                      @if (isset($socialNetworks) && $socialNetworks->count() > 0)
                        Los resultados para <h6 class="font-weight-bold d-inline">"{{$query}}"</h6> son:  
                      @else
                        No existen resultados para: <h6 class="font-weight-bold d-inline">"{{$query}}"</h6> 
                      @endif
                    </h6>
                  </div>
                  <div class="d-flex justify-content-start">
                  <a href="{{route('redesSociales')}}" type="submit" role="button" class="btn btn-outline-primary">Mostrar todas</a>
                  </div>
                @endif
             </div>
              <!-- Fin Resultados de búsqueda-->
              @include('common.success')
              <div class="table-responsive">
                <table class="table text-dark font-weight-bold" id="dataTable" width="100%" cellspacing="0">
                    <div class="text-right my-1 p-0">
                        <a href="{{route('redesSociales.create')}}" role="button" type="button" class="btn btn-primary text-white">Agregar <span class="fa fa-plus-circle"></span></a>
                    </div>
                  <thead class="bg-gradient-primary text-white">
                    <tr>
                      <th>Nombe</th>
                      <th>Enlace</th>
                      <th>Perfil o número</th>
                      <th>Ícono</th>
                      <th>Opciones</th>
                    </tr>
                  </thead>
                  <tfoot class="bg-gradient-primary text-white">
                    <tr>
                      <th>Nombre</th>
                      <th>Enlace</th>
                      <th>Perfil o número</th>
                      <th>Ícono</th>
                      <th>Opciones</th>
                    </tr>
                  </tfoot>
                  <tbody>
                    @if (isset($socialNetworks) && $socialNetworks ?? '')
                      @foreach ($socialNetworks as $socialNetwork)
                        <tr>
                        <td>{{$socialNetwork->icon->name}}</td>
                        <td><a target="_blank" rel="noopener" href="{{$socialNetwork->link}}">Ir al enlace de {{$socialNetwork->icon->name}}</a></td>
                        <td>{{$socialNetwork->nameProfile}}</td>
                        <td><i class="{{$socialNetwork->icon->icon}} fa-2x text-center text-primary"></i></td>
                        <td>
                        <a aria-label="Editar" href="{{route('redesSociales.edit', $socialNetwork->slug)}}" role="button" type="button" class="btn btn-info text-white my-1"><span class="fa fa-edit"></span></a>
                        <a aria-label="Eliminar" data-toggle="modal" data-target="#openModal{{$socialNetwork->slug}}" role="button" type="button" class="btn btn-danger"> <span class="fa fa-trash text-white"></span></a>
                      <!-- Modal para eliminar-->
                        <div class="modal fade" id="openModal{{$socialNetwork->slug}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                          <div class="modal-content">
                            <div class="modal-header bg-primary">
                              <h5 class="modal-title text-white" id="exampleModalLabel">Eliminar red social</h5>
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span class="text-white" aria-hidden="true">&times;</span>
                              </button>
                            </div>
                            <div class="modal-body font-weight-bold text-center">
                              <div>
                                <i class="fa fa-exclamation-triangle fa-2x text-primary"></i>
                              </div>
                              ¿Está seguro de eliminar esta red social: "{{$socialNetwork->icon->name}}" ?
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-light" data-dismiss="modal">Cancelar</button>
                            <form method="POST" action="{{route('redesSociales.destroy', $socialNetwork)}}">
                                @method('DELETE')
                                @csrf
                                  <button type="submit" class="btn btn-primary">Sí, eliminar <span class="fa fa-trash ml-2"></span></button>
                                </form>
                          </div>
                          </div>
                        </div>
                      </div>
                        </td>
                        </tr>
                        @endforeach
                    @endif
                  </tbody>
                </table>
                <div class="d-flex justify-content-center mx-auto">
                  @if (isset($socialNetworks) && $socialNetworks ?? '')
                    {{$socialNetworks->links()}}  
                  @endif
                </div>
              </div>
            </div>
          </div>
        </div>      
@endsection