routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PrincipalController@index')->name('principal');
Route::get('/perfil/{user}', 'UserProfileController@index')->name('perfilUsuario');

Auth::routes();

Route::group(['middleware'=>['auth']], function(){
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('home/redesSociales', 'SocialController');
Route::get('home/redesSociales', 'SocialController@index')->name('redesSociales');
Route::resource('home/publicaciones', 'PublicationController');
Route::get('home/publicaciones', 'PublicationController@index')->name('publicaciones');
Route::resource('home/perfil', 'ProfileController');
Route::get('home/perfil', 'ProfileController@index')->name('perfil');
});

resources/views/crudProfile/create.blade.php
@extends('layouts.templateHome')

@section('content')
{{-- @include('common.errors') --}}
<div class="row justify-content-center">
        <div class="col-12 col-lg-12 pb-5">
            <form id="form" class="form-group" method="POST" action="/home/perfil" enctype="multipart/form-data">
                    @csrf
                      <div class="card shadow-lg p-0">
                          <div class="card-header bg-primary p-0">
                              <div class="text-white text-center py-2">
                                  <h3 class="font-weight-bold"> Registro de perfil</h3>
                              </div>
                          </div>
                          <div class="card-body p-0">
                            <div class="form-group col-12 col-lg-11 mx-auto">
                                <div class="input-group mb-2 my-3 mx-auto">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text bg-gradient-primary"><i aria-label="icon" class="fa fa-pen-square text-white"></i></div>
                                    </div>
                                <textarea aria-label="Biografía" type="text" id="validationBiography" name="biography" class="form-control" placeholder="Escriba su biografía" required>{{old('biography')}}</textarea>
                                </div>
                                @error('biography')
                                    <small class="text-danger d-block font-weight-bold my-0">{{$message}} <i class="fa fa-exclamation-triangle"></i> </small>
                                @enderror
                                <div class="input-group mb-2 my-3 mx-auto">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text bg-gradient-primary"> <i class="fa fa-hand-point-up text-white"></i> </div>
                                    </div>
                                    <select aria-label="Motivo" id="validationReason" class="custom-select" name="music_id" required>
                                      <option disabled selected value="">-- Selecciona el tipo de música que haces --</option>
                                      @if (isset($music) && $music ?? '')
                                        @foreach ($music as $m)
                                    <option  value="{{$m->id}}" {{old('music_id') == $m->id ? 'selected': ''}}>{{$m->type}}</option>
                                        @endforeach
                                        </select>  
                                      @endif
                                </div>
                                @error('music_id')
                                    <small class="text-danger d-block font-weight-bold my-0">{{$message}} <i class="fa fa-exclamation-triangle"></i> </small>
                                @enderror
                                <label class="d-block text-dark" for="Avatar">Avatar</label>
                                <div class="custom-file">
                                <input aria-label="Avatar" id="validationAvatar" type="file" accept="image/*" name="avatar" class="custom-file-input" required>
                                  <label class="custom-file-label" for="avatar">Pinchame</label>
                                  <small class="text-primary">El avatar no debe superar los <b>5 MB</b></small>
                                </div> 
                                @error('avatar')
                                    <small class="text-danger d-block font-weight-bold my-0">{{$message}} <i class="fa fa-exclamation-triangle"></i> </small>
                                @enderror
                                <div class="mx-auto my-4">
                                    <a href="{{route('perfil')}}" class="btn btn-light mx-auto my-1"> <i class="fa fa-arrow-left mr-2"></i>Volver</a>
                                    <button id="btnSubmit" class="btn btn-primary ml-2 mx-auto">Guardar <i class="fa fa-cloud-upload-alt ml-2"></i></button>
                                </div>
                            </div>  
                            </div>    
                          </div>
                      </div>
                  </form>
              </div>
@endsection

resources/views/crudProfile/edit.blade.php
@extends('layouts.templateHome')

@section('content')
{{-- @include('common.errors') --}}
<div class="row justify-content-center">
        <div class="col-12 col-lg-12 pb-5">
            <form id="form" class="form-group" method="POST" action="/home/perfil/{{$profile->id}}" enctype="multipart/form-data">
                @method('PUT')
                    @csrf
                      <div class="card shadow-lg p-0">
                          <div class="card-header bg-primary p-0">
                              <div class="text-white text-center py-2">
                                  <h3 class="font-weight-bold"> Actualización de perfil</h3>
                              </div>
                          </div>
                          <div class="card-body p-0">
                            <div class="form-group col-12 col-lg-11 mx-auto">
                                <label class="d-block text-dark my-2" for="reason">Biografía</label>
                                <div class="input-group mb-2 my-1 mx-auto">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text bg-gradient-primary"><i name="icon" class="fa fa-pen-square text-white"></i></div>
                                    </div>
                                <textarea aria-label="Biografía" type="text" id="validationBiography" name="biography" class="form-control" placeholder="Escriba su biografía" required>{{$profile->biography}}</textarea>
                                </div>
                                @error('biography')
                                    <small class="text-danger d-block font-weight-bold my-0">{{$message}} <i class="fa fa-exclamation-triangle"></i> </small>
                                @enderror
                                <label class="d-block text-dark my-1" for="music_id">Tipo de música</label>
                                    <div class="input-group mb-2 my-1 mx-auto">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text bg-gradient-primary"> <i class="fa fa-hand-point-up text-white"></i> </div>
                                        </div>
                                        <select aria-label="Motivo" id="validationMusic" class="custom-select" name="music_id" required>
                                          <option disabled selected value="">-- Seleccione el tipo de música que hace --</option>
                                          @if (isset($music) && $music ?? '')
                                            @foreach ($music as $m)
                                        <option  value="{{$m->id}}" @if(isset($profile->music_id) && $m->id == $profile->music_id) selected @endif>{{$m->type}}</option>
                                            @endforeach
                                            </select>  
                                          @endif
                                    </div>
                                    @error('music_id')
                                        <small class="text-danger d-block font-weight-bold my-0">{{$message}} <i class="fa fa-exclamation-triangle"></i> </small>
                                     @enderror
                                <label class="d-block text-dark" for="Avatar">Avatar</label>
                                <div class="custom-file">
                                <input aria-label="Avatar" id="validationAvatar" type="file" accept="image/*" name="avatar" class="custom-file-input">
                                  <label class="custom-file-label" for="avatar">Pinchame</label>
                                  <small class="text-primary">El avatar no debe superar los <b>5 MB</b></small>
                                </div> 
                                @error('avatar')
                                    <small class="text-danger d-block font-weight-bold my-0">{{$message}} <i class="fa fa-exclamation-triangle"></i> </small>
                                @enderror
                                <div class="mx-auto my-4">
                                    <a href="{{route('perfil')}}" class="btn btn-light mx-auto my-1"> <i class="fa fa-arrow-left mr-2"></i>Volver</a>
                                    <button id="btnSubmit" class="btn btn-primary ml-2 mx-auto">Actualizar <i class="fa fa-cloud-upload-alt ml-2"></i></button>
                                </div>
                            </div>  
                            </div>    
                          </div>
                      </div>
                  </form>
              </div>
@endsection

resources/views/crudProfile/index.blade.php
@extends('layouts.templateHome')

@section('content')
          <div class="card shadow-lg mb-4 p-0">
            <div class="card-header bg-primary py-3">
              <h4 class="m-0 font-weight-bold text-white">Panel de administración de perfil</h4>
            </div>
            <div class="card-body">
              <div class="container-fluid p-0">
              @include('common.success')
              @if (Auth::User()->profile->count() == 0)
                <div class="text-right my-1 p-0">
                    <a href="{{route('perfil.create')}}" role="button" type="button" class="btn btn-primary text-white">Agregar <span class="fa fa-plus-circle"></span></a>
                </div> 
              @endif
              <div class="row my-2">
                  @if (isset($profile) && $profile ?? '')
                    @foreach ($profile as $p)
                    <div class="card col-12 p-0">
                      <div class="row no-gutters">
                        <div class="col-12 col-md-4">
                        <img src="/images/avatars/{{$p->avatar}}" class="card-img-top img-fluid" alt="Mi avatar" title="Mi avatar">
                        </div>
                        <div class="col-12 col-md-8">
                          <div class="card-body text-dark">
                            <h3 class="card-title font-weight-bold font-italic">{{Auth::User()->getStageName()}} - {{Auth::User()->getFullName()}}</h3>
                            <h5 class="card-text font-weight-bold font-italic">{{$p->music->type}} <i class="fas fa-music text-primary ml-1"></i></h5>
                            <h5 class="card-text font-weight-bold font-italic">{{Auth::User()->city->name.'/'.Auth::User()->city->region}} <i class="fas fa-city ml-1"></i></h5>
                            <address>{{Auth::User()->email}} <i class="fas fa-envelope text-primary ml-2"></i></address>
                            <p class="card-text">{{$p->biography}}</p>
                            <div class="socials">
                              @foreach ($user as $u)
                                  @foreach ($u->socialNetworks as $socialNetwork)
                                    @if ($socialNetwork->link ?? '') 
                                      <a href="{{$socialNetwork->link}}" target="_blank" rel="noopener" title="{{$socialNetwork->nameProfile}}"><i class="{{$socialNetwork->icon->icon}} fa-3x text-primary"></i></a>
                                    @else
                                      <i class="{{$socialNetwork->icon->icon}} fa-3x text-primary ml-1" title="{{$socialNetwork->nameProfile}}"></i>
                                    @endif
                                  @endforeach
                              @endforeach
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="col-12">
                      <div class="d-flex justify-content-end my-1">
                               <a href="{{route('perfil.edit', $p->id)}}" role="button" type="button" class="btn btn-primary text-white">Editar <span class="fa fa-edit"></span></a>
                     </div>
                    </div>
                    @endforeach
                  @endif
              </div>
            </div>
          </div>
        </div>     
@endsection