routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PrincipalController@index')->name('principal');
Route::get('/perfil/{user}', 'UserProfileController@index')->name('perfilUsuario');

Auth::routes();

Route::group(['middleware'=>['auth']], function(){
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('home/redesSociales', 'SocialController');
Route::get('home/redesSociales', 'SocialController@index')->name('redesSociales');
Route::resource('home/publicaciones', 'PublicationController');
Route::get('home/publicaciones', 'PublicationController@index')->name('publicaciones');
Route::resource('home/perfil', 'ProfileController');
Route::get('home/perfil', 'ProfileController@index')->name('perfil');
});

resources/views/crudPublications/create.blade.php
@extends('layouts.templateHome')

@section('content')
{{-- @include('common.errors') --}}
<div class="row justify-content-center">
        <div class="col-12 col-lg-12 pb-5">
            <form id="form" class="form-group" method="POST" action="/home/publicaciones" enctype="multipart/form-data">
                    @csrf
                      <div class="card shadow-lg p-0">
                          <div class="card-header bg-primary p-0">
                              <div class="text-white text-center py-2">
                                  <h3 class="font-weight-bold"> Registro de publicación</h3>
                              </div>
                          </div>
                          <div class="card-body p-0">
                            <div class="form-group col-12 col-lg-11 mx-auto">
                                <div class="input-group mb-2 my-3 mx-auto">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text bg-gradient-primary"><i name="icon" class="fa fa-heading text-white"></i></div>
                                    </div>
                                <input aria-label="Título" type="text" id="validationTitle" name="title" class="form-control" value="{{old('title')}}" placeholder="Ingrese el título de su publicación" required>
                                </div>
                                @error('title')
                                    <small class="text-danger d-block font-weight-bold my-0">{{$message}} <i class="fa fa-exclamation-triangle"></i> </small>
                                @enderror
                                <div class="input-group mb-2 my-3 mx-auto">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text bg-gradient-primary"><i name="icon" class="fa fa-pen-square text-white"></i></div>
                                    </div>
                                <textarea aria-label="Título" type="text" id="validationDescription" name="description" class="form-control" placeholder="Ingrese la descripción de su publicación" required>{{old('description')}}</textarea>
                                </div>
                                @error('description')
                                    <small class="text-danger d-block font-weight-bold my-0">{{$message}} <i class="fa fa-exclamation-triangle"></i> </small>
                                @enderror
                                <div class="input-group mb-2 my-3 mx-auto">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text bg-gradient-primary"> <i class="fa fa-hand-point-up text-white"></i> </div>
                                    </div>
                                    <select aria-label="Motivo" id="validationReason" class="custom-select" name="reason_id" required>
                                      <option disabled selected value="">-- Escoga el motivo de su publicación --</option>
                                      @if (isset($reasons) && $reasons ?? '')
                                        @foreach ($reasons as $reason)
                                    <option  value="{{$reason->id}}" {{old('reason_id') == $reason->id ? 'selected': ''}}>{{$reason->type}}</option>
                                        @endforeach
                                        </select>  
                                      @endif
                                </div>
                                @error('reason_id')
                                    <small class="text-danger d-block font-weight-bold my-0">{{$message}} <i class="fa fa-exclamation-triangle"></i> </small>
                                @enderror
                                <label class="d-block text-dark" for="Image">Imagen</label>
                                <div class="custom-file">
                                <input aria-label="Imagen" id="validationImage" type="file" accept="image/*" name="image" value="{{old('image')}}" class="custom-file-input" required>
                                  <label class="custom-file-label" for="Image">Pinchame</label>
                                  <small class="text-primary">La imagen no debe superar los <b>5 MB</b></small>
                                </div> 
                                @error('image')
                                    <small class="text-danger d-block font-weight-bold my-0">{{$message}} <i class="fa fa-exclamation-triangle"></i> </small>
                                @enderror
                                <div class="row">
                                    <div class="col">
                                        <label class="text-dark d-block my-1" for="Enlace">Enlace</label>
                                        <div class="input-group mb-2 my-1 mx-auto">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text bg-gradient-primary"><i name="icon" class="fa fa-link text-white"></i></div>
                                            </div>
                                        <input aria-label="Enlace" type="url" id="validationLink" name="link" class="form-control" value="{{old('link')}}" placeholder="Ingrese el link o enlace (Incluya https">
                                    </div>
                                    @error('link')
                                            <small class="text-danger d-block font-weight-bold my-0">{{$message}} <i class="fa fa-exclamation-triangle"></i> </small>
                                    @enderror
                                    </div>
                                    <div class="col">                       
                                        <label class="text-dark d-block my-1" for="Iframe">Iframe</label>
                                        <div class="input-group mb-2 my-1 mx-auto">
                                                <div class="input-group-prepend">
                                                    <div class="input-group-text bg-gradient-primary"><i name="icon" class="fa fa-video text-white"></i></div>
                                                </div>
                                            <input aria-label="Iframe" type="text" id="validationIframe" name="iframe" class="form-control" value="{{old('iframe')}}" placeholder="Ingrese el iframe que ofrece Youtube, SundCloud, etc.">
                                        </div>
                                        <small class="text-primary my-1">El campo <b>'Iframe'</b> puede quedar vacío.</small>
                                    </div>
                                </div>
                            <div class="row">
                                <div class="col">
                                    <label for="date">Fecha en base al motivo</label>
                                    <div class="input-group mx-auto">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text bg-gradient-primary"><i name="icon" class="fa fa-calendar text-white"></i></div>
                                        </div>
                                    <input aria-label="Fecha" type="date" id="validationDate" name="date" class="form-control" value="{{old('date')}}" placeholder="Ingrese la fecha en base al motivo">
                                    </div>
                                    <small class="text-primary">El campo <b>'Fecha'</b> puede quedar vacío.</small>
                                    @error('date')
                                        <small class="text-danger d-block font-weight-bold my-0">{{$message}} <i class="fa fa-exclamation-triangle"></i> </small>
                                    @enderror
                                </div>
                                <div class="col">
                                    <label for="date">Hora en base al motivo</label>
                                    <div class="input-group mx-auto">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text bg-gradient-primary"><i name="icon" class="fa fa-calendar text-white"></i></div>
                                        </div>
                                    <input aria-label="Hora" type="time" id="validationTime" name="time" class="form-control" value="{{old('time')}}" placeholder="Ingrese la hora en base al motivo">
                                    </div>
                                    <small class="text-primary">El campo <b>'Hora'</b> puede quedar vacío.</small>
                                    @error('time')
                                        <small class="text-danger d-block font-weight-bold my-0">{{$message}} <i class="fa fa-exclamation-triangle"></i> </small>
                                    @enderror   
                                </div>
                            </div>
                                <div class="mx-auto my-4">
                                    <a href="{{route('publicaciones')}}" class="btn btn-light mx-auto my-1"> <i class="fa fa-arrow-left mr-2"></i>Volver</a>
                                    <button id="btnSubmit" class="btn btn-primary ml-2 mx-auto">Guardar <i class="fa fa-cloud-upload-alt ml-2"></i></button>
                                </div>
                            </div>    
                          </div>
                      </div>
                  </form>
              </div>
@endsection

resources/views/crudPublications/edit.blade.php
@extends('layouts.templateHome')

@section('content')
<div class="row justify-content-center">
        <div class="col-12 col-lg-12 pb-5">
          @if (isset($publication) && $publication ?? '') 
            <form id="form" class="form-group" method="POST" action="/home/publicaciones/{{$publication->slug}}" enctype="multipart/form-data">
                @method('PUT')
                        @csrf
                          <div class="card shadow-lg">
                              <div class="card-header bg-primary p-0">
                                  <div class="text-white text-center py-2">
                                      <h3 class="font-weight-bold"> Actualización de publicación</h3>
                                  </div>
                              </div>
                              <div class="card-body p-0">
                                <div class="form-group col-12 col-lg-11 mx-auto">
                                    <label class="d-block text-dark my-2" for="title">Título</label>
                                    <div class="input-group mb-2 my-1 mx-auto">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text bg-gradient-primary"><i name="icon" class="fa fa-heading text-white"></i></div>
                                        </div>
                                    <input aria-label="Título" type="text" id="validationTitle" name="title" class="form-control" value="{{$publication->title}}" placeholder="Ingrese el título de su publicación" required>
                                    </div>
                                    @error('title')
                                        <small class="text-danger d-block font-weight-bold my-0">{{$message}} <i class="fa fa-exclamation-triangle"></i> </small>
                                     @enderror
                                     <label class="d-block text-dark my-1" for="description">Descripción</label>
                                    <div class="input-group mb-2 my-1 mx-auto">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text bg-gradient-primary"><i name="icon" class="fa fa-pen-square text-white"></i></div>
                                        </div>
                                    <textarea aria-label="Descripción" type="text" id="validationDescription" name="description" class="form-control" placeholder="Ingrese la descripción de su publicación" required>{{$publication->description}}</textarea>
                                    </div>
                                    @error('description')
                                        <small class="text-danger d-block font-weight-bold my-0">{{$message}} <i class="fa fa-exclamation-triangle"></i> </small>
                                     @enderror
                                     <label class="d-block text-dark my-1" for="reason">Motivo</label>
                                    <div class="input-group mb-2 my-1 mx-auto">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text bg-gradient-primary"> <i class="fa fa-hand-point-up text-white"></i> </div>
                                        </div>
                                        <select aria-label="Motivo" id="validationReason" class="custom-select" name="reason_id" required>
                                          <option disabled selected value="">-- Escoga el motivo de su publicación --</option>
                                          @if (isset($reasons) && $reasons ?? '')
                                            @foreach ($reasons as $reason)
                                        <option  value="{{$reason->id}}" @if(isset($publication->reason_id) && $reason->id == $publication->reason_id) selected @endif>{{$reason->type}}</option>
                                            @endforeach
                                            </select>  
                                          @endif
                                    </div>
                                    @error('reason_id')
                                        <small class="text-danger d-block font-weight-bold my-0">{{$message}} <i class="fa fa-exclamation-triangle"></i> </small>
                                     @enderror
                                    <label class="d-block text-dark" for="Image">Imagen</label>
                                    <div class="custom-file">
                                      <input aria-label="Imagen" id="validationImage" type="file" accept="image/*" name="image" class="custom-file-input">
                                      <label class="custom-file-label" for="Image">Pinchame</label>
                                      <small class="text-primary">La imagen no debe superar los <b>5 MB</b></small>
                                    </div>
                                    @error('image')
                                        <small class="text-danger d-block font-weight-bold my-0">{{$message}} <i class="fa fa-exclamation-triangle"></i> </small>
                                     @enderror
                                     <div class="row">
                                         <div class="col">
                                            <label class="d-block text-dark my-1" for="link">Enlace</label>
                                            <div class="input-group mb-2 my-1 mx-auto">
                                                <div class="input-group-prepend">
                                                    <div class="input-group-text bg-gradient-primary"><i name="icon" class="fa fa-link text-white"></i></div>
                                                </div>
                                            <input aria-label="Enlace" type="url" id="validationLink" name="link" class="form-control" value="{{$publication->link}}" placeholder="Ingrese el link o enlace (Incluya https)">
                                            </div>
                                            @error('link')
                                                <small class="text-danger d-block font-weight-bold my-0">{{$message}} <i class="fa fa-exclamation-triangle"></i> </small>
                                            @enderror
                                         </div>
                                         <div class="col">
                                            <label class="d-block text-dark my-1" for="link">Iframe</label>
                                            <div class="input-group mb-2 my-1 mx-auto">
                                                <div class="input-group-prepend">
                                                    <div class="input-group-text bg-gradient-primary"><i name="icon" class="fa fa-video text-white"></i></div>
                                                </div>
                                            <input aria-label="Iframe" type="text" id="validationIframe" name="iframe" class="form-control" value="{{$publication->iframe}}" placeholder="Ingrese el iframe que ofrece Youtube, SundCloud, etc.">
                                            </div>
                                             <small class="text-primary">El campo <b>'Iframe'</b> puede quedar vacío.</small>
                                         </div>
                                     </div>
                                <div class="row">
                                    <div class="col">
                                        <label class="d-block text-dark" for="date">Fecha en base al motivo</label>
                                        <div class="input-group mx-auto">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text bg-gradient-primary"><i name="icon" class="fa fa-calendar text-white"></i></div>
                                            </div>
                                        <input aria-label="Fecha" type="date" id="validationDate" name="date" class="form-control" value="{{$publication->date}}" placeholder="Ingrese la fecha en base al motivo">
                                        </div>
                                        <small class="text-primary">El campo <b>'Fecha'</b> puede quedar vacío.</small>
                                        @error('date')
                                            <small class="text-danger d-block font-weight-bold my-0">{{$message}} <i class="fa fa-exclamation-triangle"></i> </small>
                                        @enderror
                                    </div>
                                    <div class="col">
                                        <label class="d-block text-dark" for="time">Hora en base al motivo</label>
                                        <div class="input-group mx-auto">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text bg-gradient-primary"><i name="icon" class="fa fa-calendar text-white"></i></div>
                                            </div>
                                        <input aria-label="Hora" type="time" id="validationTime" name="time" class="form-control" value="{{$publication->time}}" placeholder="Ingrese la hora en base al motivo">
                                        </div>
                                        <small class="text-primary">El campo <b>'Hora'</b> puede quedar vacío.</small>
                                        @error('time')
                                            <small class="text-danger d-block font-weight-bold my-0">{{$message}} <i class="fa fa-exclamation-triangle"></i> </small>
                                        @enderror
                                    </div>
                                </div>
                                    <div class="mx-auto my-4">
                                        <a href="{{route('publicaciones')}}" class="btn btn-light mx-auto my-1"> <i class="fa fa-arrow-left mr-2"></i>Volver</a>
                                        <button id="btnSubmit" class="btn btn-primary ml-2 mx-auto">Actualizar <i class="fa fa-cloud-upload-alt ml-2"></i></button>
                                    </div>
                              </div>
                          </div>
                      </form>
                @endif
              </div>
        </div>
@endsection

resources/views/crudPublications/index.blade.php
@extends('layouts.templateHome')

@section('content')
          <div class="card shadow-lg mb-4 p-0">
            <div class="card-header bg-primary py-3">
              <h4 class="m-0 font-weight-bold text-white">Panel de administración de publicaciones</h4>
            </div>
            <div class="card-body">
              <div class="container-fluid p-0">
              @include('common.success')
                    <div class="text-right my-1 p-0">
                        <a href="{{route('publicaciones.create')}}" role="button" type="button" class="btn btn-primary text-white">Agregar <span class="fa fa-plus-circle"></span></a>
                    </div>
              <div class="row my-2">
                  @if (isset($publications) && $publications ?? '')
                    @foreach ($publications as $publication)
                    <div class="col-12 col-sm-6 col-md-6 col-lg-6 col-xl-6 my-2">
                        <div class="card mb-3 shadow-sm h-100">
                        <img height="350px" width="200px" src="/images/publicaciones/{{$publication->image}}" class="card-img-top" alt="Imagen de publicación" title="Imagen de {{$publication->title}}">
                            <div class="card-body text-dark">
                                <h4 class="card-title font-weight-bold text-uppercase">{{$publication->title}}</h4>
                                <h5 class="badge badge-primary card-title text-uppercase font-weight-bold py-2 mx-auto">{{$publication->reason->type}}</h5>
                                <p class="card-subtitle">{{$publication->description}}</p>
                                @if ($publication->date ?? '' && $publication->time)
                                  <p class="card-subtitle text-dark my-1">{{$publication->date}} a las {{Str::limit($publication->time, $limit="5", $end=".")}}</p>
                                @else
                                  <p class="card-subtitle text-dark my-1">Sin fecha por el momento</p>
                                @endif
                                <a href="{{$publication->link}}" target="_blank" rel="noopener" class="text-primary">Ir al enlace</a>
                                <p class="card-subtitle text-left my-1"><small class="text-dark">Creado el: <b>{{$publication->created_at}}</b></small></p>
                                <p class="card-subtitle text-left my-1"><small class="text-dark">Editado el: <b>{{$publication->updated_at}}</b></small></p>
                                <div class="text-left">
                                  <a aria-label="Editar" href="{{route('publicaciones.edit', $publication->slug)}}" role="button" type="button" class="btn btn-info text-white"><span class="fa fa-edit"></span></a>    
                                  <a aria-label="Eliminar" data-toggle="modal" data-target="#openModal{{$publication->id}}" role="button" type="button" class="btn btn-danger"> <span class="fa fa-trash text-white"></span></a>
                                </div>
                                <div class="modal fade" id="openModal{{$publication->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                  <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                      <div class="modal-header bg-primary text-white">
                                        <h5 class="modal-title font-weight-bold" id="exampleModalLabel">Eliminar publicación</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                          <span class="text-white active" aria-hidden="true">&times;</span>
                                        </button>
                                        </div>
                                        <div class="modal-body font-weight-bold">
                                          <div class="text-center">
                                            <i class="fa fa-exclamation-triangle fa-2x text-primary"></i>
                                          </div>
                                          ¿Está seguro de eliminar esta publicación: "{{$publication->title}}" ?
                                        </div>
                                        <div class="modal-footer">
                                          <button type="button" class="btn btn-light" data-dismiss="modal">Cancelar</button>
                                          <form method="POST" action="{{route('publicaciones.destroy', $publication)}}">
                                            @method('DELETE')
                                            @csrf
                                              <button type="submit" class="btn btn-primary">Sí, eliminar <span class="fa fa-trash ml-2"></span></button>
                                            </form>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                            </div>
                            </div>
                      </div>
                    @endforeach
                  @endif
              </div>
              @if (isset($publications) && $publications ?? '')
                  <div class="d-flex justify-content-center">
                    {{$publications->links()}}
                  </div>
              @endif
            </div>
          </div>
        </div>      
@endsection